version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - database:/app/db

volumes:
  database:
    driver: local


# version: '3'
# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - 8080:8080
#     volumes:
#       - database:/app/db

# volumes:
#   database:


# version: '3'
# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - 8080:8080
#     volumes:
#       - database:/app/db

# volumes:
#   database:
#     driver: local
